version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
      - export TAG_TIMESTAMP=`date +%s`
      - export REPOSITORY_URI=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/$IMAGE_REPO_NAME
  build:
    commands:
      - echo Build started on `date`
      - echo Download config file
      - echo Building the Docker image...
      - cd SSO-Frontend
      - docker build -t $IMAGE_REPO_NAME:${ENV}-latest .
      - docker tag $IMAGE_REPO_NAME:${ENV}-latest ${REPOSITORY_URI}:${ENV}-latest
      - docker tag $IMAGE_REPO_NAME:${ENV}-latest ${REPOSITORY_URI}:${TAG_TIMESTAMP}
  post_build:
    commands:
        - echo Build completed on `date`
        - echo Pushing the Docker image...
        - docker push ${REPOSITORY_URI}:${ENV}-latest
        - docker push ${REPOSITORY_URI}:${TAG_TIMESTAMP}
        - echo Writing image definitions file...
        - printf '[{"name":"%s","imageUri":"%s"}]' $CONTAINER_NAME ${REPOSITORY_URI}:${TAG_TIMESTAMP} > imagedefinitions.json
artifacts:
    files:
        - SSO-Frontend/imagedefinitions.json
