version: '3'
services:
  node-app:
    image: "node:10"
    volumes:
      - ./:/app
    env_file: .env
    working_dir: /app
    ports:
      - "4000:4000"
    command: ["npm", "run", "start:server"]
    container_name: SSO-Frontend

# networks:
#   default:
#     external:
#       name: backend2_default